# -*- coding: utf-8 -*-
"""Amazon_Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154YY4mNFlWT4b5ok77O44ChRArzo84gq

# Amazon Sales Analysis

## Mini Project

**Name:** Yamjala Meghana

**Technology Used:** Python, Pandas, Matplotlib, Google Colab

## Project Objective

The objective of this project is to analyze Amazon sales data and identify business insights such as sales performance, customer behavior, product performance, payment preferences, and monthly sales trends.

Import Libraries
"""

import os

os.listdir()

import pandas as pd

df = pd.read_csv('/content/Amazon.csv')

"""Dataset Loading"""

df.head()

"""Dataset Overview"""

df.shape

df.columns

df.dtypes

df.describe()

"""KPI ANALYSIS"""

df["TotalAmount"].sum()

df["OrderID"].count()

df["TotalAmount"].mean()

df["TotalAmount"].max()

df["TotalAmount"].min()

"""Sale Analysis"""

sales_by_state = df.groupby("State")["TotalAmount"].sum()

sales_by_state = df.groupby("State")["TotalAmount"].sum()
sales_by_state

sales_by_state.sort_values(ascending=False)

"""Sales by Category"""

sales_by_category = df.groupby("Category")["TotalAmount"].sum()
sales_by_category

sales_by_category.sort_values(ascending=False)

df.columns

"""Top 10 Products by Sales"""

top_products = df.groupby("ProductName")["TotalAmount"].sum()
 top_products

top_products.sort_values(ascending=False).head(10)

"""Top 5 Customers by Sales"""

top_customers = df.groupby("CustomerName")["TotalAmount"].sum()
top_customers

top_customers.sort_values(ascending=False).head(5)

"""Payment Mode Analysis"""

payment_mode = df ["PaymentMethod"].value_counts()
payment_mode

"""Monthly Sales Trend"""

df ["OrderDate"] = pd.to_datetime(df ["OrderDate"])

df["Month"] = df["OrderDate"].dt.strftime("%B")

monthly_sales = df.groupby ("Month") ["TotalAmount"].sum()
monthly_sales

"""Sales by State Chart"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

sales_by_state.sort_values(ascending=False).plot(kind="bar")

plt.title("Sales by State")
plt.xlabel("State")
plt.ylabel("Total Sales")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()

plt.show()

"""Sales by Category (Pie Chart)"""

sales_by_category.plot(
    kind="pie",
    autopct="%1.1f%%",
    figsize=(7,7))
plt.title("Sales by Category")
plt.ylabel("")
plt.show()

"""Monthly Sales Trend (Line Chart)"""

monthly_sales.plot(
    kind="line",
    marker="o",
    figsize=(10,5)
)
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks (rotation=45)
plt.show()

"""Top 10 Products by Sales (Bar Chart)"""

top_products.sort_values(ascending=False).head(10).plot(
    kind="barh",
    figsize=(10,6)
)
plt.title("Top 10 Products by Sales")
plt.xlabel("Total Sales")
plt.ylabel("Product Name")
plt.show()